name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank You for the Issue.  I will try to get to look at it as soon as I can.'
        pr-message: 'Thank you for the PR.  I really appreciate all submissions.  I will try to take a look at it as soon as I can.'
